### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by bojidar-bg** [launchscout/angular-googleapi#16]
As the last commit seems to be from 2014, I wonder if this repo is now dead...

**Comment by oshliaer** [comment]
@bojidar-bg but it works fine.

**Comment by fer** [comment]
@oshliaer it does! but it'd be nice to have a look to the issue list, merge some branches and additionally add some testing. 

Maybe @superchris can throw some light here.

**Comment by superchris** [comment]
I hadn't really been using it for quite awhile, but now I'm looking at porting this to angular2 so I'll have a look thru these issues at PRs
